version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb-container
    restart: always
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend-image
    container_name: backend_container
    ports:
      - "8000:8000"
    volumes:
      - node_modules:/app/node_modules
      - .:/app
    restart: always
    env_file:
      - .env
    depends_on:
      - mongodb

volumes:
  data:
  node_modules:
